window.DEMO_DATA = {
  paperTitle: "MMTSE Demo",
  samples: [
    {
      id: "case-01",
      label: "Case 01",
      title: "Two speakers, close semantic overlap",
      scene:
        "A competitive overlap case where both speakers discuss related content, so semantic cues alone are informative but not always sufficient.",
      notes: [
        "Target 1 is more front-left and visually clear.",
        "Target 2 is semantically similar, which stresses prompt disambiguation.",
      ],
      references: {
        mixture: {
          label: "Mixture",
          path: "./assets/audio/case-01/mixture.wav",
          available: false,
        },
        target1: {
          label: "Ground Truth Target 1",
          path: "./assets/audio/case-01/target-1.wav",
          available: false,
        },
        target2: {
          label: "Ground Truth Target 2",
          path: "./assets/audio/case-01/target-2.wav",
          available: false,
        },
      },
      targetProfiles: [
        {
          id: "target-1",
          label: "Target 1",
          title: "Target Speaker 1",
          promptSummary: "Female speaker, left-front sector, visually reliable",
          baselineMixSiSnr: "-3.4 dB",
          bestSubset: "pre+main+av",
        },
        {
          id: "target-2",
          label: "Target 2",
          title: "Target Speaker 2",
          promptSummary: "Male speaker, rear-right sector, text partially ambiguous",
          baselineMixSiSnr: "-2.9 dB",
          bestSubset: "pre+text+main+av",
        },
      ],
      subsets: [
        {
          key: "pre",
          rank: 11,
          modalities: ["pre"],
          meanSiSnri: 7.8,
          targetScores: { "target-1": 8.4, "target-2": 7.2 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre.wav",
            "target-2": "./assets/audio/case-01/target-2/pre.wav",
          },
          available: false,
          note: "Enrollment alone already stabilizes speaker identity, but remains vulnerable in severe overlap.",
        },
        {
          key: "text",
          rank: 15,
          modalities: ["text"],
          meanSiSnri: 5.1,
          targetScores: { "target-1": 5.6, "target-2": 4.6 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/text.wav",
            "target-2": "./assets/audio/case-01/target-2/text.wav",
          },
          available: false,
          note: "Semantic prompting helps, but confusion rises when both speakers share topic and style.",
        },
        {
          key: "main",
          rank: 14,
          modalities: ["main"],
          meanSiSnri: 5.7,
          targetScores: { "target-1": 6.2, "target-2": 5.2 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/main.wav",
            "target-2": "./assets/audio/case-01/target-2/main.wav",
          },
          available: false,
          note: "Spatial prompting is helpful when direction is discriminative, but can degrade for nearby sectors.",
        },
        {
          key: "av",
          rank: 13,
          modalities: ["av"],
          meanSiSnri: 6.3,
          targetScores: { "target-1": 7.1, "target-2": 5.5 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/av.wav",
            "target-2": "./assets/audio/case-01/target-2/av.wav",
          },
          available: false,
          note: "Visual cues improve robustness when articulation is visible, but do not fully resolve all ambiguities.",
        },
        {
          key: "pre+text",
          rank: 10,
          modalities: ["pre", "text"],
          meanSiSnri: 8.9,
          targetScores: { "target-1": 9.4, "target-2": 8.4 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre+text.wav",
            "target-2": "./assets/audio/case-01/target-2/pre+text.wav",
          },
          available: false,
          note: "Identity and semantics complement each other, especially for lexical overlap.",
        },
        {
          key: "pre+main",
          rank: 6,
          modalities: ["pre", "main"],
          meanSiSnri: 10.6,
          targetScores: { "target-1": 11.4, "target-2": 9.8 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre+main.wav",
            "target-2": "./assets/audio/case-01/target-2/pre+main.wav",
          },
          available: false,
          note: "Speaker identity plus spatial guidance is often a strong low-cost fusion baseline.",
        },
        {
          key: "pre+av",
          rank: 7,
          modalities: ["pre", "av"],
          meanSiSnri: 10.1,
          targetScores: { "target-1": 11.1, "target-2": 9.1 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre+av.wav",
            "target-2": "./assets/audio/case-01/target-2/pre+av.wav",
          },
          available: false,
          note: "Identity and lip-body evidence reinforce target consistency under heavy overlap.",
        },
        {
          key: "text+main",
          rank: 12,
          modalities: ["text", "main"],
          meanSiSnri: 8.0,
          targetScores: { "target-1": 8.6, "target-2": 7.4 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/text+main.wav",
            "target-2": "./assets/audio/case-01/target-2/text+main.wav",
          },
          available: false,
          note: "Semantics plus direction beats either alone, but still lacks explicit speaker identity.",
        },
        {
          key: "text+av",
          rank: 9,
          modalities: ["text", "av"],
          meanSiSnri: 9.2,
          targetScores: { "target-1": 9.9, "target-2": 8.5 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/text+av.wav",
            "target-2": "./assets/audio/case-01/target-2/text+av.wav",
          },
          available: false,
          note: "Visual speech helps the text branch reject semantically similar interference.",
        },
        {
          key: "main+av",
          rank: 8,
          modalities: ["main", "av"],
          meanSiSnri: 9.7,
          targetScores: { "target-1": 10.5, "target-2": 8.9 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/main+av.wav",
            "target-2": "./assets/audio/case-01/target-2/main+av.wav",
          },
          available: false,
          note: "Spatial and visual geometry combine well when the scene is directionally structured.",
        },
        {
          key: "pre+text+main",
          rank: 5,
          modalities: ["pre", "text", "main"],
          meanSiSnri: 11.2,
          targetScores: { "target-1": 12.0, "target-2": 10.4 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre+text+main.wav",
            "target-2": "./assets/audio/case-01/target-2/pre+text+main.wav",
          },
          available: false,
          note: "Three cues give both identity, semantics, and geometry, reducing prompt uncertainty.",
        },
        {
          key: "pre+text+av",
          rank: 4,
          modalities: ["pre", "text", "av"],
          meanSiSnri: 11.8,
          targetScores: { "target-1": 12.5, "target-2": 11.1 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre+text+av.wav",
            "target-2": "./assets/audio/case-01/target-2/pre+text+av.wav",
          },
          available: false,
          note: "Visual evidence boosts lexical grounding when acoustic overlap is aggressive.",
        },
        {
          key: "pre+main+av",
          rank: 2,
          modalities: ["pre", "main", "av"],
          meanSiSnri: 12.9,
          targetScores: { "target-1": 13.9, "target-2": 11.9 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre+main+av.wav",
            "target-2": "./assets/audio/case-01/target-2/pre+main+av.wav",
          },
          available: false,
          note: "Identity, direction, and video form the strongest cue set when semantics are less distinctive.",
        },
        {
          key: "text+main+av",
          rank: 3,
          modalities: ["text", "main", "av"],
          meanSiSnri: 12.1,
          targetScores: { "target-1": 12.8, "target-2": 11.4 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/text+main+av.wav",
            "target-2": "./assets/audio/case-01/target-2/text+main+av.wav",
          },
          available: false,
          note: "A strong identity-free fusion case that still approaches full fusion performance.",
        },
        {
          key: "pre+text+main+av",
          rank: 1,
          modalities: ["pre", "text", "main", "av"],
          meanSiSnri: 13.6,
          targetScores: { "target-1": 14.4, "target-2": 12.8 },
          audio: {
            "target-1": "./assets/audio/case-01/target-1/pre+text+main+av.wav",
            "target-2": "./assets/audio/case-01/target-2/pre+text+main+av.wav",
          },
          available: false,
          note: "Full fusion gives the cleanest target recovery and the highest SI-SNRi on this case.",
        },
      ],
    },
    {
      id: "case-02",
      label: "Case 02",
      title: "Spatially separated but visually noisy",
      scene:
        "A scene where directional cues are reliable, yet visual evidence is partially corrupted and enrollment quality becomes critical.",
      notes: [
        "Target 1 benefits strongly from spatial prompting.",
        "Target 2 highlights the cost of degraded visual evidence.",
      ],
      references: {
        mixture: {
          label: "Mixture",
          path: "./assets/audio/case-02/mixture.wav",
          available: false,
        },
        target1: {
          label: "Ground Truth Target 1",
          path: "./assets/audio/case-02/target-1.wav",
          available: false,
        },
        target2: {
          label: "Ground Truth Target 2",
          path: "./assets/audio/case-02/target-2.wav",
          available: false,
        },
      },
      targetProfiles: [
        {
          id: "target-1",
          label: "Target 1",
          title: "Target Speaker 1",
          promptSummary: "Spatial cue dominates, enrollment remains stable",
          baselineMixSiSnr: "-4.0 dB",
          bestSubset: "pre+main",
        },
        {
          id: "target-2",
          label: "Target 2",
          title: "Target Speaker 2",
          promptSummary: "Visual stream is noisy, full fusion is still safest",
          baselineMixSiSnr: "-3.1 dB",
          bestSubset: "pre+text+main+av",
        },
      ],
      subsets: [],
    },
  ],
};
